// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using callList.Data;

#nullable disable

namespace callList.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("callList.Data.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "elena@siva.sk",
                            FirstName = "Elena",
                            LastName = "Siva",
                            PhoneNumber = "+421905342347"
                        },
                        new
                        {
                            Id = 2,
                            Email = "elena@siva.sk",
                            FirstName = "Elena",
                            LastName = "Siva",
                            PhoneNumber = "+421905342347"
                        },
                        new
                        {
                            Id = 3,
                            Email = "elena@siva.sk",
                            FirstName = "Elena",
                            LastName = "Siva",
                            PhoneNumber = "+421905342347"
                        },
                        new
                        {
                            Id = 4,
                            Email = "elena@siva.sk",
                            FirstName = "Elena",
                            LastName = "Siva",
                            PhoneNumber = "+421905342347"
                        },
                        new
                        {
                            Id = 5,
                            Email = "elena@siva.sk",
                            FirstName = "Elena",
                            LastName = "Siva",
                            PhoneNumber = "+421905342347"
                        },
                        new
                        {
                            Id = 6,
                            Email = "elena@siva.sk",
                            FirstName = "Elena",
                            LastName = "Siva",
                            PhoneNumber = "+421905342347"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
